### ISSUE TITLE
How to detect double tapping?

### ISSUE THREAD

**Issue by wongzigii** [RafaelKayumov/RKTabView#13]
Hi @RafaelKayumov 
I am currently working on a feature that when user double tapping the tab item, the tableView or scrollView will automatically scroll to top and trigger the pull down refresh so that the tableView will refresh the data.

I am using RKTabView as the tab bar.

**Comment by wongzigii** [comment]
I tried to add tap gesture recognizer to `RKTabItem` as follow , but the `RKTabItem` is subclassing of `NSObject` instead of `UIView`.

    for (int i = 0; i < tabView.tabItems.count; i ++) {
        UITapGestureRecognizer *doubleTap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleDoubleTapGesture)];
        doubleTap.numberOfTapsRequired = 2;
        [tabView.tabItems[i] addGestureRecognizer:doubleTap];
    }

So the above will throw exception.

**Comment by RafaelKayumov** [comment]
Hi @wongzigii 
Yes you are right. `RKTabItem` is just an object template for future view and it has nothing to do with gesture recognizers itself. For now it does not support custom gestures. It should be implemented as additional feature. I'll see what I can do.

**Comment by wongzigii** [comment]
Thanks for your quick response. Glad to see this feature one day.

**Comment by RafaelKayumov** [comment]
Hi @wongzigii. Added new item with custom gesture #14. Check `ButtonItemsExampleController` for example.
