### ISSUE TITLE
Programmatically switch tabs

### ISSUE THREAD

**Issue by aakashs** [RafaelKayumov/RKTabView#17]
Hi, is there a way to programmatically switch from one Excludable element to another? 

I attempted to do this by calling switchState() on a non selected tab, which changes its image to the selected state image, but does not perform its action or deselect the previously selected tab.

Since only one excludable tab is meant to be able to appear selected at a time, is this a bug?

Thank you!

**Comment by RafaelKayumov** [comment]
Hi @aakashs. `switchState` method only reverses `tabState` enum value and does not affect other items. It should be considered as private. It placed to public header - my omission. Have you tried `switchTabIndex:` method of `RKTabView` to switch tabs?

**Comment by aakashs** [comment]
Cool, thank you. I just tried switchTabIndex: and it seems this method also only switches the image but does not perform the action. 

I might be missing something but I haven't been able to figure out how to properly programmatically switch tab state for any of the 3 types of tabs, have you ever experienced this?

More specifically, I'm trying to find a way to programmatically deselect an Unexcludable Item

**Comment by RafaelKayumov** [comment]
@aakashs I see... I think you should call action manually as you switch tab manually(programmatically). Also, as temporary solution, you can create private category for `RKTabView` and declare `switchTab:notify:`method which is already in `RKTabView` but it's private, so you can call it in your code. Pass desired item and `YES` for `notify` param to call delegate action.
Desired solution is to update `switchTabIndex:` method to also accept `BOOL notify` parameter. May be I'll add this in next version.
